//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Приложение
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Abonents_SavarovskiyIR330Entities2 : DbContext
    {
        private static Abonents_SavarovskiyIR330Entities2 _context;
        public Abonents_SavarovskiyIR330Entities2()
            : base("name=Abonents_SavarovskiyIR330Entities2")
        {
        }
        public static Abonents_SavarovskiyIR330Entities2 GetContext()
        {
            if (_context == null)
                _context = new Abonents_SavarovskiyIR330Entities2();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Абоненты> Абоненты { get; set; }
        public virtual DbSet<Разговоры> Разговоры { get; set; }
        public virtual DbSet<Тарифы> Тарифы { get; set; }
        public virtual DbSet<Телефоны> Телефоны { get; set; }
    }
}
