//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Приложение
{
    using System;
    using System.Collections.Generic;
    
    public partial class Разговоры
    {
        public short ID_Разговора { get; set; }
        public short Номер_Города { get; set; }
        public string Телефон { get; set; }
        public System.DateTime Дата_Разговора { get; set; }
        public int Продолжительность { get; set; }
        public string Состояние_Оплаты { get; set; }
    
        public virtual Тарифы Тарифы { get; set; }
        public virtual Телефоны Телефоны { get; set; }
    }
}
