//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Приложение
{
    using System;
    using System.Collections.Generic;
    
    public partial class Телефоны
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Телефоны()
        {
            this.Разговоры = new HashSet<Разговоры>();
        }
    
        public string ID_Телефона { get; set; }
        public short ID_Абонента { get; set; }
        public string Номер_Договора { get; set; }
        public System.DateTime Дата_Установки { get; set; }
    
        public virtual Абоненты Абоненты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Разговоры> Разговоры { get; set; }
    }
}
